### ISSUE TITLE
Video doesn't change upon selecting different SOW

### ISSUE THREAD

**Issue by tpilvelis-gw** [filetrust/gw-sow-presentation#68] opened 2020-02-28 16:19 UTC
Reproduction Steps:
Play a video on  1.D.1 and the video plays,
on switching to 1.D.2 the video previously playing is still playing even though the text content has changed

The src of the tag has changed upon inspection however the video hasn't changed

**Comment by gw-sbirch** [comment] 2020-03-02 14:18
I can't reproduce this on edge or firefox

**Comment by ahewitt-glasswall** [comment] 2020-03-02 14:40
Going to ask vinh to have a look and close it if it's fixed.

**Closed** 2020-03-02 15:04 UTC
